CREATE ROLE logl WITH LOGIN UNENCRYPTED PASSWORD 'pwned';
CREATE DATABASE logl0 WITH OWNER logl;
CREATE DATABASE logl1 WITH OWNER logl;
CREATE DATABASE logl2 WITH OWNER logl;
CREATE DATABASE logl3 WITH OWNER logl;
CREATE DATABASE logl4 WITH OWNER logl;
CREATE DATABASE logl5 WITH OWNER logl;
CREATE DATABASE logl6 WITH OWNER logl;
CREATE DATABASE logl7 WITH OWNER logl;
CREATE DATABASE logl8 WITH OWNER logl;
CREATE DATABASE logl9 WITH OWNER logl;

